// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm3wlOfnFotWFgBPjRedF6xvqcQ2liP5M',
    appId: '1:894304909933:web:3d1679738afd157649dd64',
    messagingSenderId: '894304909933',
    projectId: 'explorachiapas-f3120',
    authDomain: 'explorachiapas-f3120.firebaseapp.com',
    storageBucket: 'explorachiapas-f3120.firebasestorage.app',
    measurementId: 'G-W3DEJL8S1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSuWlIXdrWJRyXDmNOHkD3Kg86FXu9wi4',
    appId: '1:894304909933:android:66de62b3a5b89e4349dd64',
    messagingSenderId: '894304909933',
    projectId: 'explorachiapas-f3120',
    storageBucket: 'explorachiapas-f3120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-FsiTmGS0wuDtSjom6sNCMpVwSPGZjU',
    appId: '1:894304909933:ios:eff7ef86b5dffbb549dd64',
    messagingSenderId: '894304909933',
    projectId: 'explorachiapas-f3120',
    storageBucket: 'explorachiapas-f3120.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg-FsiTmGS0wuDtSjom6sNCMpVwSPGZjU',
    appId: '1:894304909933:ios:eff7ef86b5dffbb549dd64',
    messagingSenderId: '894304909933',
    projectId: 'explorachiapas-f3120',
    storageBucket: 'explorachiapas-f3120.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm3wlOfnFotWFgBPjRedF6xvqcQ2liP5M',
    appId: '1:894304909933:web:d18fa1eeec2cecb449dd64',
    messagingSenderId: '894304909933',
    projectId: 'explorachiapas-f3120',
    authDomain: 'explorachiapas-f3120.firebaseapp.com',
    storageBucket: 'explorachiapas-f3120.firebasestorage.app',
    measurementId: 'G-VP8YG30TT7',
  );
}
